### PR TITLE
Don't use deprecated org.gradle.util.GFileUtils

### LINKED ISSUE #568: Remove usage of org.gradle.util.GFileUtils
[PidCollector.java:16 calls org.gradle.util.GFileUtils](https://github.com/gradle/gradle-profiler/blob/1125b1ed8223d4f8f5ce57b4ac48232d6ce65b53/subprojects/build-operations/src/main/java/org/gradle/trace/pid/PidCollector.java#L12) and that method has been deprecated and will be removed in Gradle 9.0

https://ge.androidx.dev/s/nzodz7gwiblhy/deprecations?expanded=WyIyNCIsIjQiXQ&expanded-stacktrace=WyIyNiJd

### PR DESCRIPTION
**Pull request by ov7a**
Fixes #568

### CODE REVIEW

File: subprojects/build-operations/src/main/java/org/gradle/trace/pid/AbstractPidCollectorBuildService.java [hunk 1]
```diff
@@ -26,7 +28,11 @@ public interface Parameters extends BuildServiceParameters {
     }
 
     protected AbstractPidCollectorBuildService() {
-        GFileUtils.writeFile(getPid().toString(), getParameters().getPidFile().get().getAsFile());
+        try (FileWriter writer = new FileWriter(getParameters().getPidFile().get().getAsFile())) {
+            writer.write(getPid().toString());
```
Comment (asodja) [inline subprojects/build-operations/src/main/java/org/gradle/trace/pid/AbstractPidCollectorBuildService.java:32]: 💅 Can we maybe simplify it and just use `Files.write`?:
```
        try {
            Files.write(getParameters().getPidFile().get().getAsFile().toPath(), getPid().toString().getBytes(StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
 ```
 ?

Comment (ov7a) [reply subprojects/build-operations/src/main/java/org/gradle/trace/pid/AbstractPidCollectorBuildService.java]: I don't have a strong opinion about it, but it feels more mouthful. I've updated it

**Review by asodja — APPROVED** [review]
LGTM
